[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.5.0-rc.4"
egui = "0.23"
eframe = "0.23"
egui_plot = "0.23"
egui_extras = "0.23"
csv = "1.3.0"
